### ISSUE TITLE
自动批量完成理符任务问题

### ISSUE THREAD

**Issue by DeepseaXX** [AtmoOmen/DailyRoutines#1]
开启了YesAlready的自动完成任务后，日志提示报错之后停止不动。
```
2024-01-18 18:25:06.972 +09:00 [WRN] [ECommons] [Daily Routines] Clearing 0 remaining tasks because of timeout
2024-01-18 18:25:06.972 +09:00 [WRN] [ECommons] [Daily Routines] Task ClickHqSubmit took too long to execute
   at ECommons.Automation.TaskManager.Tick(Object _) in D:\young\Documents\GitHub\DailyRoutines\ECommons\ECommons\Automation\TaskManager.cs:line 284
```

关闭了YesAlready之后，卡在任务完成界面，提示类似的报错，如果立刻手动点击任务完成则提示`Clearing 9 remaining tasks`并卡住不动，如果稍等一会再手动点击任务完成则可顺利进入下一轮（我也不知道为什么会这样好神奇）。

```
2024-01-18 18:30:48.487 +09:00 [WRN] [ECommons] [Daily Routines] Clearing 1 remaining tasks because of timeout
2024-01-18 18:30:48.487 +09:00 [WRN] [ECommons] [Daily Routines] Task ClickSelectQuest took too long to execute
   at ECommons.Automation.TaskManager.Tick(Object _) in D:\young\Documents\GitHub\DailyRoutines\ECommons\ECommons\Automation\TaskManager.cs:line 284
```

补充：
自己又试了一下，问题出在两个Task之间间隔时间太短，跟Yes没什么关系。

**Comment by AtmoOmen** [comment]
麻烦告知一下插件版本

**Comment by DeepseaXX** [comment]
就是刚从库里拖的版本，0.0.0.3

**Comment by AtmoOmen** [comment]
啊, 新一轮的流程判断出了问题, 我等会推送一个新版本解决这个问题

**Comment by AtmoOmen** [comment]
0.0.0.4 版本已更新, 请通过我的在线库或者本仓库 Release 进行更新, 查看是否相同的问题会再次出现。

因为我大号的理符限额已经耗尽, 因此主要基于 5.0 理符进行测试, 如果有任何情况, 请及时回复。
