### ISSUE TITLE
部分角色无法使用/pdr submarine进行房屋交互

### ISSUE THREAD

**Issue by EUEUE39** [AtmoOmen/DailyRoutines#120]
插件版本号 0.5.2.0
复现：角色在白银乡可正常执行/pdr submarine，但角色在薰衣草苗圃无法执行/pdr submarine
不知部队房所在地址是否影响执行该命令，但是每次执行都是下线前角色在工坊内部，下线后重登角色在部队门正前方
日志
```
12:43:31.921 | ERR | [Command] Error while dispatching command "/pdr" (Argument: "submarine")
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at DailyRoutines.Modules.AutoSubmarineCollect.get_WorkshopTerritory() in D:\封徵\Document\GitHub\DailyRoutines\DailyRoutines\Modules\UIOperation\AutoSubmarineCollect.cs:line 49
	   at DailyRoutines.Modules.AutoSubmarineCollect.EnqueueTeleportTasks() in D:\封徵\Document\GitHub\DailyRoutines\DailyRoutines\Modules\UIOperation\AutoSubmarineCollect.cs:line 139
	   at DailyRoutines.Managers.CommandManager.OnCommandPDR(String command, String args) in D:\封徵\Document\GitHub\DailyRoutines\DailyRoutines\Managers\Game\CommandManager.cs:line 135
	   at Dalamud.Game.Command.CommandManager.DispatchCommand(String command, String argument, CommandInfo info)
```

**Comment by AtmoOmen** [comment]
已经在测试版修复该问题, 预计7月初推送下一个正式版
