### ISSUE TITLE
V0.5.3.3加载错误

### ISSUE THREAD

**Issue by distance011** [AtmoOmen/DailyRoutines#128]
![LH$15DC67XD6~@ZFW{VMM}H](https://github.com/AtmoOmen/DailyRoutines/assets/55056320/32c3a4e0-0274-4a98-b433-c41146af8472)
从V0.5.3.2更新至V0.5.3.3安装失败，重启游戏后显示加载错误，删除installedPlugins和pluginConfigs的文件，重装后依旧提示失效

**Comment by AtmoOmen** [comment]
请提供 `/xllog` 里的相关报错日志

**Comment by distance011** [comment]
15:14:51.947 | ERR | [LOCALPLUGIN] Error while loading Daily Routines
	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.PlatformNotSupportedException: No voice installed on the system or none available with the current security setting.
	   at System.Speech.Internal.Synthesis.VoiceSynthesis..ctor(WeakReference speechSynthesizer)
	   at System.Speech.Synthesis.SpeechSynthesizer.get_VoiceSynthesizer()
	   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputToNull()
	   at DailyRoutines.Notifications.TextToTalk.Init() in D:\封徵\Document\GitHub\DailyRoutines\DailyRoutines\Notifications\TextToTalk.cs:line 14
	   at DailyRoutines.Managers.NotifyManager.Init() in D:\封徵\Document\GitHub\DailyRoutines\DailyRoutines\Managers\NotifyManager.cs:line 27
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
	   at DailyRoutines.Managers.Service.Init(DalamudPluginInterface pluginInterface) in D:\封徵\Document\GitHub\DailyRoutines\DailyRoutines\Managers\Service.cs:line 36
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope)
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading)

**Comment by AtmoOmen** [comment]
电脑未安装任何 TTS 组件
