### ISSUE TITLE
自动跳过对话和自动提交物品问题

### ISSUE THREAD

**Issue by DeepseaXX** [AtmoOmen/DailyRoutines#2]
自动完成理符任务时打开自动跳过对话和自动提交物品选项，第一次正常完成，第二次以后均会卡在每个npc的第一次对话和提交物品的环节。log分别如下
（并且log是在卡住的时候疯狂拉屎，一小会拉了30M）
```
23:29:01.825 ERR |    at DailyRoutines.Modules.AutoRequestItemSubmit.ClickRequestIcon() in D:\young\Documents\GitHub\DailyRoutines\DailyRoutines\Modules\Base\AutoRequestItemSubmit.cs:line 67
```

```
23:30:01.383 ERR | [AddonLifecycle] Exception in OnAddonDraw post-draw invoke.
23:30:01.383 ERR | System.NullReferenceException: Object reference not set to an instance of an object.
23:30:01.383 ERR |    at DailyRoutines.Modules.AutoTalkSkip.OnAddonDraw(AddonEvent type, AddonArgs args) in D:\young\Documents\GitHub\DailyRoutines\DailyRoutines\Modules\Base\AutoTalkSkip.cs:line 24
23:30:01.383 ERR |    at Dalamud.Game.AddonLifecycle.AddonLifecycle.InvokeListeners(AddonEvent eventType, AddonArgs args)
23:30:01.383 ERR |    at Dalamud.Game.AddonLifecycle.AddonLifecycle.OnAddonDraw(AtkUnitBase* addon)

```

**Comment by AtmoOmen** [comment]
重启游戏可以解决问题吗?

**Comment by AtmoOmen** [comment]
已经两周没有后续反馈, 现关闭该 Issue，如有任何后续反馈，请打开一个新的 Issue
