### ISSUE TITLE
自动回收幻卡导致崩溃

### ISSUE THREAD

**Issue by status102** [AtmoOmen/DailyRoutines#39]
### 表现
开始后正常回收，持有的幻卡回收完后仍处于激活（开始按钮invalid）并崩溃

### 可能的相关信息
开了好像是`SimpleTweaksPlugin`中的一个回收幻卡时，自动调整回收个数至最大，不知道是否有互相影响

### Log
```
Unhandled native exception occurred at ffxiv_dx11.exe+BACBCC
Code: C0000005
Dump at: ****
System Time: 2024-03-29 02:24:19.1148289

   at DailyRoutines.Managers.AddonManager.CallbackRaw(AtkUnitBase* Base, Int32 valueCount, AtkValue* values, Byte updateState)
   at DailyRoutines.Managers.AddonManager.Callback(AtkUnitBase* Base, Boolean updateState, Object[] values)
   at ECommons.Automation.TaskManager.<>c__DisplayClass37_0.<Enqueue>b__0()
   at ECommons.Automation.TaskManager.Tick(Object _)
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act)
   at Dalamud.Utility.EventHandlerExtensions.InvokeSafely(OnUpdateDelegate updateDelegate, Framework framework)
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework)

Exception Info #0
Address: C0000005
Flags: 0
Address: 7FF66334CBCC
Parameters: 0, 0
Call Stack
{
  [0]	ffxiv_dx11.exe+BACBCC
  [1]	ffxiv_dx11.exe+BACBCC
  [2]	ffxiv_dx11.exe+568173
  [3]	ffxiv_dx11.exe+56A7B4
  [4]	ffxiv_dx11.exe+53BDB0
  [5]	7FF8FF9C49EC
  [6]	173FDD87020
  [7]	173E92F34F8
  [8]	3EE293F440
  [9]	7FF900FE4BED
  [10]	F40592ACD0B7
  [11]	coreclr.dll+3FA548	(coreclr_shutdown+0x44EE8)
  [12]	FFFFFFFFFFFFFFFF
}

Registers
{
  RAX:	0
  RBX:	3
  RCX:	1732B34D160 [ffxiv_dx11.exe+1A87738	(GFSDK_SSAO_CreateContext_D3D11+0x402928)]
  RDX:	0
  R8:	173B3A08160 [44004900000003]
  R9:	3
  R10:	ffxiv_dx11.exe+1A87738	(GFSDK_SSAO_CreateContext_D3D11+0x402928)
  R11:	1732B34D160 [ffxiv_dx11.exe+1A87738	(GFSDK_SSAO_CreateContext_D3D11+0x402928)]
  R12:	0
  R13:	173B3A08160 [44004900000003]
  R14:	1732B34D160 [ffxiv_dx11.exe+1A87738	(GFSDK_SSAO_CreateContext_D3D11+0x402928)]
  R15:	3EE293F280 [316CE]
  RSI:	0
  RDI:	0
  RBP:	3EE293F1E0
  RSP:	3EE293F0E0 [5590388]
  RIP:	ffxiv_dx11.exe+BACBCC [98D2694890148B]
}

Stack
{
  [RSP+0]	5590388
  [RSP+8]	B6
  [RSP+10]	1B4802773D0 [1736C175A00]
  [RSP+18]	coreclr.dll+1A349 [17860B850FC73B]
  [RSP+20]	0
  [RSP+28]	0
  [RSP+30]	0
  [RSP+38]	1736C175A00 [1736C170D20]
  [RSP+40]	3E00000003
  [RSP+48]	1736C170000
  [RSP+50]	1736C1702B0 [104000501030004]
  [RSP+58]	7FF900000000 [7FF8FFECA130]
  [RSP+60]	0
  [RSP+68]	17300000000
  [RSP+70]	0
  [RSP+78]	0
}
```
[crash-20240329102443.zip](https://github.com/AtmoOmen/DailyRoutines/files/14798436/crash-20240329102443.zip)

**Comment by AtmoOmen** [comment]
可能是在界面还未刷新时强制触发了回调导致的崩溃, 可能需要一定程度的小小重写

**Comment by status102** [comment]
0.0.3.41更新后测试未复现
